import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer  from "@/components/footer/Footer";
import { ThemeProvider } from "@/components/theme-provider";
import { Manrope } from 'next/font/google';
 
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
const manrope = Manrope({ subsets: ['latin'], weight: ['400', '700'] });
 
export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en">
      <body className={manrope.className}>
        <ThemeProvider attribute="class" defaultTheme="light" enableSystem>
          <Header />
          {children}
          <Footer />
        </ThemeProvider>
      </body>
    </html>
  );
}